import { GIT_MASTER_COMMIT_ATOMIC_PLANNING_SECTION_ZH } from "./commit-atomic-planning.zh"
import { GIT_MASTER_COMMIT_CONTEXT_ANALYSIS_SECTION_ZH } from "./commit-context-analysis.zh"
import { GIT_MASTER_COMMIT_EXECUTION_VERIFICATION_SECTION_ZH } from "./commit-execution-verification.zh"

export const GIT_MASTER_COMMIT_WORKFLOW_SECTION_ZH = [
	GIT_MASTER_COMMIT_CONTEXT_ANALYSIS_SECTION_ZH,
	GIT_MASTER_COMMIT_ATOMIC_PLANNING_SECTION_ZH,
	GIT_MASTER_COMMIT_EXECUTION_VERIFICATION_SECTION_ZH,
].join("\n\n---\n\n")
